import type { CmsHelpGuide } from "@/lib/cmsHelp/types";
import { tour } from "@/lib/cmsHelp/tourSelectors";
import { detailedListModuleGuide, detailedSettingsGuide } from "@/lib/cmsHelp/sharedSteps";
import { buildPageEditorGuide } from "@/lib/cmsHelp/pageEditorGuide";

export const CMS_HELP_GUIDES: CmsHelpGuide[] = [
  {
    id: "dashboard",
    group: "Overview",
    title: "Dashboard",
    icon: "fa-solid fa-house",
    summary: "Your home base — site stats, quick actions, activity feed, and shortcuts to every module.",
    steps: [
      {
        title: "Dashboard hero — greeting and date",
        body: "The Dashboard is the first screen after login. The hero banner greets you and shows today's date.",
        details: [
          "Good morning / afternoon / evening changes based on time of day.",
          "The date helps confirm you are in the current session.",
          "This area sets context before you manage content.",
        ],
        target: tour.dashboardHero,
        route: "/dashboard",
        placement: "bottom",
      },
      {
        title: "Quick create buttons in the hero",
        body: "These buttons jump directly to common create screens without using the sidebar.",
        details: [
          "New Page — opens the visual page builder create screen.",
          "News — opens Create News.",
          "Files — opens the File Manager for uploads.",
        ],
        target: tour.dashboardActions,
        route: "/dashboard",
        placement: "left",
      },
      {
        title: "Content metric cards — Pages, Albums, News",
        body: "Three large cards summarize how much content exists. Click any card to open that module.",
        details: [
          "Pages — total CMS pages on your website.",
          "Albums — banner slideshow albums available.",
          "News — news articles in the system.",
          "Numbers show — while loading, then update with real counts.",
          "Each card is a clickable shortcut to Manage Pages, Manage Albums, or Manage News.",
        ],
        target: tour.dashboardStats,
        route: "/dashboard",
        placement: "bottom",
      },
      {
        title: "Quick links row",
        body: "Secondary shortcuts for frequent admin tasks beyond the three main metrics.",
        details: [
          "Visual page builder — same as creating a new page.",
          "Website settings — company info, logo, integrations.",
          "Navigation menu — manage site menus.",
          "Team & users — manage admin user accounts.",
        ],
        target: tour.dashboardQuicklinks,
        route: "/dashboard",
        placement: "bottom",
      },
      {
        title: "Website summary panel",
        body: "The lower grid shows a compact website overview with key counts and health indicators.",
        details: [
          "Review totals at a glance.",
          "Use this before planning content updates.",
        ],
        target: tour.dashboardActivity,
        route: "/dashboard",
        placement: "top",
      },
      {
        title: "Recent activity feed",
        body: "See what changed recently — edits, creates, and logins from your team.",
        details: [
          "Each entry shows who did what and when.",
          "Helpful for teams sharing one CMS.",
          "For the full log, open Settings → Manage Audit Trail.",
        ],
        target: tour.dashboardActivity,
        route: "/dashboard",
        placement: "top",
      },
      {
        title: "Sidebar — your profile block",
        body: "Your avatar and name appear at the top of the sidebar on every screen.",
        details: [
          "Confirms which admin account is active.",
          "Avatar matches the top-right account button.",
        ],
        target: tour.sidebarUser,
        route: "/dashboard",
        placement: "right",
      },
      {
        title: "Sidebar — CMS module navigation",
        body: "All modules live here: Pages, Banners, Files, Menu, News, Settings, Users, Account Management.",
        details: [
          "Click a parent label (e.g. Pages) to expand sub-links.",
          "Sub-links include Manage and Create screens.",
          "The active page is highlighted in purple.",
        ],
        target: tour.sidebar,
        route: "/dashboard",
        placement: "right",
      },
      {
        title: "View Website — preview the live site",
        body: "Always verify public changes by opening the live website.",
        details: [
          "Opens in a new tab so you do not lose your admin work.",
          "Compare CMS edits with what visitors see.",
        ],
        target: tour.sidebarViewSite,
        route: "/dashboard",
        placement: "right",
        tip: "Bookmark the public URL for quick checks after every publish.",
      },
      {
        title: "Top bar — Help guide and account",
        body: "Click your avatar for Account, Help (this guide), and Logout.",
        details: [
          "Help opens the live tour for whatever page you are on.",
          "Use the sidebar toggle to hide/show the sidebar on desktop.",
        ],
        target: tour.topbarAvatar,
        route: "/dashboard",
        placement: "bottom",
      },
    ],
  },

  detailedListModuleGuide({
    id: "pages",
    group: "Pages",
    title: "Manage Pages",
    icon: "fa-solid fa-file-lines",
    summary: "Complete guide to listing, searching, filtering, editing, and creating website pages.",
    navHref: "/pages",
    navLabel: "Manage Pages",
    parentMenu: "Pages",
    createLabel: "Create Page",
    entityName: "pages",
    entitySingular: "page",
    searchHint: "Search matches page titles and related text.",
    filterNotes: [
      "Show deleted only — opens trash view for soft-deleted pages.",
      "Visibility filters in Advanced Search: Published, Private, Draft.",
    ],
    actionNotes: ["Bulk Delete — removes all selected pages (may move to trash)."],
    optionIcons: [
      "Click the page title link — opens the visual editor.",
      "Pencil icon — edit the page.",
      "Trash icon — delete the page.",
      "Status badges show Published, Private, or Draft.",
    ],
    extraSteps: [
      {
        title: "Page presets (if available)",
        body: "Some setups include Presets for reusable page templates. Check Pages → Presets in the sidebar.",
        route: "/pages",
        placement: "center",
      },
    ],
  }),

  buildPageEditorGuide("create"),
  buildPageEditorGuide("edit"),

  {
    id: "banners-home",
    group: "Banners",
    title: "Manage Home Banners",
    icon: "fa-solid fa-panorama",
    summary: "Every part of the homepage hero carousel — slides, media, text, order, and save.",
    steps: [
      {
        title: "Open Manage Home Banners",
        body: "Banners → Manage Home Banners. This is separate from Manage Albums.",
        details: [
          "Home Banners = what appears on the homepage hero.",
          "Manage Albums = reusable slideshow groups used elsewhere.",
        ],
        target: tour.nav("/banners/home"),
        route: "/banners/home",
        placement: "right",
      },
      {
        title: "Page header and save area",
        body: "The header explains this screen controls homepage hero content.",
        target: tour.moduleHero,
        route: "/banners/home",
        placement: "bottom",
      },
      {
        title: "Slide list and previews",
        body: "Each slide represents one frame in the homepage carousel.",
        details: [
          "Image slides show a thumbnail preview.",
          "Video slides may show a player preview.",
          "Deleted or empty slides should be removed before publishing.",
        ],
        route: "/banners/home",
        placement: "center",
      },
      {
        title: "Slide fields — title, description, link",
        body: "Optional text overlays appear on top of the banner media.",
        details: [
          "Title — main headline on the slide.",
          "Description — supporting sentence below the title.",
          "Button/link — where clicking the slide should go.",
          "Keep text short for mobile readability.",
        ],
        route: "/banners/home",
        placement: "center",
      },
      {
        title: "Upload or replace media",
        body: "Replace images or videos when campaigns change.",
        details: [
          "Use high-resolution wide images (1920px or similar).",
          "Compress large files for faster loading.",
          "Videos should be short loops for hero areas.",
        ],
        route: "/banners/home",
        placement: "center",
      },
      {
        title: "Drag to reorder slides",
        body: "The first slide is what visitors see first when the homepage loads.",
        details: [
          "Grab the drag handle or slide card to move it.",
          "Put your strongest message in position 1.",
        ],
        route: "/banners/home",
        placement: "center",
        tip: "Limit homepage slides to 3–5 for best performance.",
      },
      {
        title: "Transition and timing (if shown)",
        body: "Some home banner setups inherit album transition settings.",
        route: "/banners/home",
        placement: "center",
      },
      {
        title: "Save and preview homepage",
        body: "Save all changes, then open View Website to test the carousel.",
        target: tour.sidebarViewSite,
        route: "/banners/home",
        placement: "right",
      },
    ],
  },

  detailedListModuleGuide({
    id: "banners",
    group: "Banners",
    title: "Manage Albums",
    icon: "fa-solid fa-images",
    summary: "List, search, create, edit, and delete banner albums used in slideshows across the site.",
    navHref: "/banners",
    navLabel: "Manage Albums",
    parentMenu: "Banners",
    createLabel: "Create Album",
    entityName: "albums",
    entitySingular: "album",
    searchHint: "Search by album name.",
    optionIcons: [
      "Edit — change album name, transitions, and slides.",
      "Delete — remove the album (confirm it is not used on live pages first).",
    ],
  }),

  {
    id: "banners-create",
    group: "Banners",
    title: "Create an Album",
    icon: "fa-solid fa-photo-film",
    summary: "Full walkthrough: album name, transitions, duration, type, upload, slide details, reorder, save.",
    steps: [
      {
        title: "Open Create an Album",
        target: tour.nav("/banners/create"),
        route: "/banners/create",
        placement: "right",
        body: "Banners → Create an Album.",
        details: ["Albums group multiple slides with shared transition settings."],
      },
      {
        title: "Album Settings section",
        body: "Configure the album identity and slideshow behavior.",
        target: tour.settingsSection,
        route: "/banners/create",
        placement: "bottom",
        details: [
          "Album Name — internal label (e.g. Homepage Rotator, Promo Q1).",
          "Transition In — animation when slide enters (fade, slide, etc.).",
          "Transition Out — animation when slide exits.",
          "Duration slider — seconds each slide stays visible (1–10).",
          "Banner Type pills — Image or Video (changes upload accept type).",
        ],
      },
      {
        title: "Stats cards — album name, slide count",
        body: "The hero stats update as you work — slide count increases with each upload.",
        target: tour.moduleStats,
        route: "/banners/create",
        placement: "bottom",
      },
      {
        title: "Upload zone — drag and drop",
        body: "Add one or many files at once.",
        target: tour.uploadZone,
        route: "/banners/create",
        placement: "bottom",
        details: [
          "Drag files onto the dashed area.",
          "Or click Browse to pick from your computer.",
          "Image mode: JPG, PNG, WebP.",
          "Video mode: MP4, WebM, etc.",
        ],
      },
      {
        title: "Slide preview cards",
        body: "Each uploaded file becomes a card with preview, title, description, and remove button.",
        details: [
          "Preview shows image or video player.",
          "Title — optional overlay headline.",
          "Description — optional supporting text.",
          "Remove slide — deletes that slide from the album.",
        ],
        route: "/banners/create",
        placement: "center",
      },
      {
        title: "Reorder slides",
        body: "Drag the grip handle on each card to change playback order.",
        route: "/banners/create",
        placement: "center",
      },
      {
        title: "Save Album footer",
        body: "Click Save Album. Cancel returns without saving.",
        target: tour.settingsFormFooter,
        route: "/banners/create",
        placement: "top",
        details: [
          "All required album settings must be filled.",
          "At least one slide is typically required.",
        ],
      },
    ],
  },

  detailedListModuleGuide({
    id: "files",
    group: "Files",
    title: "File Manager",
    icon: "fa-solid fa-folder-open",
    summary: "Upload, folder navigation, file preview, copy URL, rename, and delete assets.",
    navHref: "/files",
    navLabel: "Files",
    parentMenu: "Files",
    createLabel: "Upload",
    entityName: "files",
    entitySingular: "file",
    searchHint: "Search by file or folder name.",
    optionIcons: [
      "Click a file to preview or copy its URL.",
      "Delete — remove unused assets.",
      "Upload — add new images or documents.",
    ],
    extraSteps: [
      {
        title: "Using files in Pages and News",
        body: "Copy the file URL and paste into image blocks or news upload fields.",
        details: [
          "Prefer WebP or optimized JPG for web performance.",
          "Delete only files not referenced on live pages.",
        ],
        route: "/files",
        placement: "center",
      },
    ],
  }),

  detailedListModuleGuide({
    id: "menu",
    group: "Menu",
    title: "Manage Menu",
    icon: "fa-solid fa-bars",
    summary: "List menus, search, create, edit navigation trees, and verify on the public site.",
    navHref: "/menu",
    navLabel: "Manage Menu",
    parentMenu: "Menu",
    createLabel: "Create Menu",
    entityName: "menus",
    entitySingular: "menu",
    searchHint: "Search by menu name.",
    optionIcons: [
      "Edit — open the menu builder with pages, URLs, and structure panels.",
      "Delete — remove unused menus.",
    ],
  }),

  {
    id: "menu-create",
    group: "Menu",
    title: "Create a Menu",
    icon: "fa-solid fa-list-check",
    summary: "Name the menu, add pages, add custom URLs, organize structure, save.",
    steps: [
      {
        title: "Menu name field",
        body: "Enter a descriptive name: Main Navigation, Footer Links, Mobile Menu.",
        target: tour.moduleHero,
        route: "/menu/create",
        placement: "bottom",
        details: ["This name is for admin reference; visitors see the link labels, not the menu name."],
      },
      {
        title: "Pages panel — search and select",
        body: "Find existing CMS pages and add them as menu links.",
        target: tour.menuPanelPages,
        route: "/menu/create",
        placement: "bottom",
        details: [
          "Use the search box to filter pages by title.",
          "Check the checkbox next to each page you want.",
          "Selected count shows at the top of the panel.",
          'Click "Add" to insert checked pages into the structure.',
        ],
      },
      {
        title: "Custom URL panel",
        body: "Add links that are not CMS pages — external sites, PDFs, anchors.",
        target: tour.menuPanelCustom,
        route: "/menu/create",
        placement: "bottom",
        details: [
          "Label — text shown in the navigation.",
          "URL — full https:// address or internal path.",
          "Target — same window or new tab for external links.",
        ],
      },
      {
        title: "Structure panel — order and nesting",
        body: "Drag items to reorder. Nest items to create dropdown sub-menus.",
        target: tour.menuPanelStructure,
        route: "/menu/create",
        placement: "bottom",
        details: [
          "Top-level items appear in the main nav bar.",
          "Indented items appear as dropdown children.",
          "Item count shows at the top of the panel.",
          "Remove items with the delete control on each row.",
        ],
        tip: "5–7 top-level links is ideal for usability.",
      },
      {
        title: "Live stats in page header",
        body: "Shows menu name and item count as you build.",
        target: tour.moduleStats,
        route: "/menu/create",
        placement: "bottom",
      },
      {
        title: "Save Menu",
        target: tour.settingsFormFooter,
        route: "/menu/create",
        placement: "top",
        body: "Click Save Menu. Cancel discards unsaved changes.",
        details: ["Verify links on View Website after saving."],
      },
    ],
  },

  detailedListModuleGuide({
    id: "news",
    group: "News",
    title: "Manage News",
    icon: "fa-solid fa-newspaper",
    summary: "List, search, filter, publish, feature, edit, and delete news articles.",
    navHref: "/news",
    navLabel: "Manage News",
    parentMenu: "News",
    createLabel: "Create News",
    entityName: "news articles",
    entitySingular: "article",
    searchHint: "Search by article title.",
    filterNotes: ["Show deleted — trash view for removed articles."],
    optionIcons: [
      "Edit — full article form with content and SEO.",
      "Delete — remove article (may support restore from trash).",
      "Featured badge — up to 3 featured on homepage.",
    ],
  }),

  {
    id: "news-create",
    group: "News",
    title: "Create News",
    icon: "fa-solid fa-pen-nib",
    summary: "Every field: title, date, category, teaser, visibility, featured, media, body, SEO, save.",
    steps: [
      {
        title: "Open Create News",
        target: tour.nav("/news/create"),
        route: "/news/create",
        placement: "right",
        body: "News → Create News.",
        details: ["Hero stats show Status, Featured, and Category as you fill the form."],
      },
      {
        title: "News Details section — title and date",
        target: tour.settingsSection,
        route: "/news/create",
        placement: "bottom",
        body: "Core article metadata.",
        details: [
          "Title — headline on the article page and listings.",
          "Date — publication date (defaults to today).",
          "Category — required; organize articles by topic.",
          "Teaser — short summary for news list cards.",
        ],
      },
      {
        title: "Visibility toggle — Published / Private",
        body: "Published articles appear on the public news section. Private stays admin-only.",
        details: [
          "Switch toggles without losing your draft content.",
          "You can publish later by editing the article.",
        ],
        route: "/news/create",
        placement: "center",
      },
      {
        title: "Featured toggle",
        body: "Featured articles can appear prominently on the homepage.",
        details: [
          "Maximum of 3 featured items site-wide.",
          "Use for major announcements only.",
        ],
        route: "/news/create",
        placement: "center",
      },
      {
        title: "Media section — banner and thumbnail",
        body: "Both images are required before saving.",
        details: [
          "Article Banner — wide hero image on the article page.",
          "Article Thumbnail — square/listing image in news grids.",
          "Click the upload card or drag a file.",
          "Supported: JPG, PNG.",
        ],
        route: "/news/create",
        placement: "center",
      },
      {
        title: "Content section — rich text editor",
        body: "Write the full story with formatting.",
        details: [
          "Bold, italic, headings, lists, and links.",
          "Paste from Word may need cleanup.",
          "Add images inline if the editor supports it.",
        ],
        route: "/news/create",
        placement: "center",
      },
      {
        title: "SEO section",
        body: "Search engine optimization fields.",
        details: [
          "SEO Title — defaults from article title on blur if empty.",
          "SEO Description — defaults from teaser if empty.",
          "SEO Keywords — comma-separated optional terms.",
        ],
        route: "/news/create",
        placement: "center",
      },
      {
        title: "Save News",
        target: tour.settingsFormFooter,
        route: "/news/create",
        placement: "top",
        body: "Click Save News. Cancel returns to Manage News without saving.",
      },
    ],
  },

  detailedListModuleGuide({
    id: "news-categories",
    group: "News",
    title: "Manage News Categories",
    icon: "fa-solid fa-folder-tree",
    summary: "Create, edit, delete, restore categories; modal create; trash view.",
    navHref: "/news/category_index",
    navLabel: "Manage News Categories",
    parentMenu: "News",
    createLabel: "Create Category",
    entityName: "categories",
    entitySingular: "category",
    searchHint: "Search by category name.",
    filterNotes: ["View Trash — deleted categories with restore option."],
    extraSteps: [
      {
        title: "Create Category modal",
        body: "Click + Create Category to open the popup form.",
        target: tour.moduleCreate,
        route: "/news/category_index",
        placement: "left",
        details: [
          "Enter Category Name only — slug may be auto-generated.",
          "Click Create Category to save.",
          "Modal closes and table refreshes automatically.",
        ],
      },
      {
        title: "Total News column",
        body: "Shows how many articles use each category.",
        target: tour.moduleTable,
        route: "/news/category_index",
        placement: "top",
        details: ["High counts mean the category is actively used."],
      },
    ],
  }),

  detailedSettingsGuide({
    id: "settings-account",
    group: "Settings",
    title: "Account Settings",
    icon: "fa-solid fa-user-gear",
    summary: "Profile photo, name, email, password — every section explained.",
    navHref: "/settings/account",
    navLabel: "Manage Account Settings",
    includeProfileStep: true,
    sections: [
      {
        name: "Personal Information",
        details: [
          "First Name and Last Name — shown in sidebar and top bar.",
          "Profile Photo upload — JPG/PNG; updates avatar everywhere after save.",
          "Click Save in the profile section footer.",
        ],
      },
      {
        name: "Email Address",
        details: [
          "Current email display.",
          "New email field — may require verification.",
          "Save email changes separately from profile.",
        ],
      },
      {
        name: "Password",
        details: [
          "Click to expand password form if collapsed.",
          "Current password — required for security.",
          "New password — use 12+ characters, mixed case, numbers.",
          "Confirm password — must match new password.",
        ],
      },
    ],
  }),

  detailedSettingsGuide({
    id: "settings-website",
    group: "Settings",
    title: "Website Settings",
    icon: "fa-solid fa-globe",
    summary: "General info, branding, logo, favicon, integrations, navigation — every section.",
    navHref: "/settings/website",
    navLabel: "Manage Website Settings",
    sections: [
      {
        name: "General",
        details: [
          "Company name — appears in admin title bar and may appear on public site.",
          "Address, phone, email — contact details for footer or contact page.",
          "Social media URLs — optional links.",
        ],
      },
      {
        name: "Branding",
        details: [
          "Company Logo — shown in admin top bar after save.",
          "Favicon — small icon in browser tabs.",
          "Use PNG with transparent background for logos.",
        ],
      },
      {
        name: "Integrations",
        details: [
          "Analytics IDs — Google Analytics, etc.",
          "Chat widgets — Freshchat or similar.",
          "Save after each integration change.",
        ],
      },
      {
        name: "Navigation",
        details: [
          "Default menu assignments if your theme supports it.",
          "Link menus created in Menu module to site locations.",
        ],
      },
    ],
  }),

  detailedListModuleGuide({
    id: "settings-audit",
    group: "Settings",
    title: "Audit Trail",
    icon: "fa-solid fa-clock-rotate-left",
    summary: "Read activity log entries — who, what, when — with search and pagination.",
    navHref: "/settings/audit",
    navLabel: "Manage Audit Trail",
    parentMenu: "Settings",
    createLabel: "Export",
    entityName: "log entries",
    entitySingular: "log entry",
    searchHint: "Search by user, action, or module keyword.",
    optionIcons: ["Each row shows timestamp, user, action description, and module affected."],
  }),

  detailedListModuleGuide({
    id: "users",
    group: "Users",
    title: "Manage Users",
    icon: "fa-solid fa-users",
    summary: "Create users, assign roles, activate/deactivate, bulk actions, edit accounts.",
    navHref: "/users",
    navLabel: "Manage Users",
    parentMenu: "Users",
    createLabel: "Create User",
    entityName: "users",
    entitySingular: "user",
    searchHint: "Search by name or email.",
    filterNotes: ["Show inactive only — users who cannot log in."],
    actionNotes: [
      "Activate — enable login for selected users.",
      "Deactivate — block login without deleting the account.",
    ],
    optionIcons: [
      "Eye — view user details.",
      "Pencil — edit name, email, role.",
      "Toggle — activate or deactivate single user.",
    ],
    extraSteps: [
      {
        title: "Create User modal — all fields",
        body: "Popup form for new admin accounts.",
        target: tour.moduleCreate,
        route: "/users",
        placement: "left",
        details: [
          "First Name — required.",
          "Last Name — required.",
          "Email — login username; must be unique.",
          "Role — pick from roles defined in Manage Roles.",
          "Click Create User to save.",
        ],
      },
      {
        title: "Active vs Inactive status",
        body: "Inactive users cannot log in but their history is preserved.",
        target: tour.moduleStats,
        route: "/users",
        placement: "bottom",
        details: [
          "Active count and Inactive count shown in stat cards.",
          "Deactivate instead of delete when someone leaves temporarily.",
        ],
      },
    ],
  }),

  detailedListModuleGuide({
    id: "roles",
    group: "Account Management",
    title: "Manage Roles",
    icon: "fa-solid fa-user-shield",
    summary: "Create and edit roles with name and description; used when assigning users.",
    navHref: "/account-management/roles",
    navLabel: "Manage Roles",
    parentMenu: "Account Management",
    createLabel: "Create Role",
    entityName: "roles",
    entitySingular: "role",
    searchHint: "Search by role name or description.",
    extraSteps: [
      {
        title: "Create Role modal",
        body: "Name and description fields.",
        target: tour.moduleCreate,
        route: "/account-management/roles",
        placement: "left",
        details: [
          "Role Name — e.g. Editor, Manager, Viewer.",
          "Description — explain permissions intent.",
          "Then configure access in Manage Access Rights.",
        ],
      },
    ],
  }),

  {
    id: "access-rights",
    group: "Account Management",
    title: "Manage Access Rights",
    icon: "fa-solid fa-key",
    summary: "Every module card, role pill, search, and save — full permission matrix guide.",
    steps: [
      {
        title: "Open Manage Access Rights",
        target: tour.nav("/account-management/access_rights"),
        route: "/account-management/access_rights",
        placement: "right",
        body: "Account Management → Manage Access Rights.",
        details: ["Controls what each role can see and do in every CMS module."],
      },
      {
        title: "Page header",
        target: tour.moduleHero,
        route: "/account-management/access_rights",
        placement: "bottom",
        body: "Describes the permission matrix purpose.",
      },
      {
        title: "Search modules",
        target: tour.moduleToolbar,
        route: "/account-management/access_rights",
        placement: "bottom",
        body: "Quickly find Pages, News, Users, etc.",
        details: ["Type module name to filter the card list."],
      },
      {
        title: "Module permission cards",
        body: "Each card is one CMS area.",
        details: [
          "Pages, News, Banners, Files, Menu, Settings, Users, etc.",
          "Expand a card to see role toggles inside.",
          "Cards may show icons matching the sidebar.",
        ],
        route: "/account-management/access_rights",
        placement: "center",
      },
      {
        title: "Role pills / toggles",
        body: "Turn each role ON or OFF for the selected module.",
        details: [
          "Admin — usually full access.",
          "Editor — content modules only.",
          "Viewer — read-only where supported.",
          "Custom roles you created appear here too.",
        ],
        route: "/account-management/access_rights",
        placement: "center",
        tip: "Grant minimum access needed — security best practice.",
      },
      {
        title: "Sticky save footer",
        target: tour.settingsFooter,
        route: "/account-management/access_rights",
        placement: "top",
        body: "Click Save to apply all permission changes.",
        details: [
          "Users may need to log out and back in.",
          "Test with a non-admin account after changes.",
        ],
      },
    ],
  },
];

export const CMS_HELP_GUIDE_MAP = Object.fromEntries(
  CMS_HELP_GUIDES.map((guide) => [guide.id, guide])
) as Record<string, import("@/lib/cmsHelp/types").CmsHelpGuide>;
